#!/bin/bash
#SBATCH -p himem
#SBATCH -c 4
#SBATCH --mem=46000M
#SBATCH -t 3-10:00                  # Runtime in D-HH:MM
#SBATCH -J WGBS_merge_markdup
#SBATCH --array=0-12               # 13 samples, index 0-12

work_path=$SLURM_SUBMIT_DIR

module load samtools/1.20
#module load sambamba/0.8.1
module load sambamba/0.7.0

set -e

if [ ! -d "${work_path}/merged_bam" ]; then
    mkdir -p "${work_path}/merged_bam"
fi

if [ ! -d "${work_path}/tmp" ]; then
    mkdir -p "${work_path}/tmp"
fi

# Input: completed_samples.txt (generated by 01_generate_lane_lists.py)
# Columns: sample_alias  n_expected  n_found  status  bam_files
# Only COMPLETE samples are processed; header line skipped with NR>1
completed_txt="${work_path}/completed_samples.txt"

# Extract only COMPLETE samples into indexed arrays
mapfile -t complete_samples < <(awk -F'\t' 'NR>1 && $4=="COMPLETE" {print $1}' "$completed_txt")
mapfile -t complete_bamlists < <(awk -F'\t' 'NR>1 && $4=="COMPLETE" {print $5}' "$completed_txt")

sample="${complete_samples[${SLURM_ARRAY_TASK_ID}]}"
bam_csv="${complete_bamlists[${SLURM_ARRAY_TASK_ID}]}"

echo "======================================"
echo "SLURM_ARRAY_TASK_ID : ${SLURM_ARRAY_TASK_ID}"
echo "Sample              : ${sample}"
echo "Start               : $(date)"
echo "======================================"

# Convert comma-separated BAM list to bash array
IFS=',' read -r -a lane_bams <<< "$bam_csv"

echo ""
echo "Found ${#lane_bams[@]} lane BAM(s):"
printf '  %s\n' "${lane_bams[@]}"

# ----------------------------------------------------------------------
# Step 1: Fix RG tags for each lane BAM (for loop, consistent with pipeline style)
#         Original mapping used lane prefix as SM and LB,
#         which prevents sambamba markdup from detecting cross-lane duplicates.
#         Fix: set SM and LB to sample-level; keep ID and PU as lane-level.
# ----------------------------------------------------------------------
echo ""
echo "--- Step 1: Fix RG tags ---"

rg_fixed_bams=()
for bam in "${lane_bams[@]}"; do
    basename=$(basename "${bam}" .bam)       # e.g. WGBS-PAIRED-tumor_4121361-SN509_..._filtered
    lane_prefix="${basename%_filtered}"      # strip _filtered to recover original lane prefix
    fixed_bam="${work_path}/tmp/${basename}.rg_fixed.bam"

    echo "  [RG fix] ${basename}"
    samtools addreplacerg \
        -r "$(printf 'ID:%s\tSM:%s\tLB:%s\tCN:PMGC\tPL:Illumina\tPU:%s' \
            "${lane_prefix}" "${sample}" "${sample}" "${lane_prefix}")" \
        -w \
        -@ 4 \
        -o "${fixed_bam}" \
        "${bam}" && echo "  ** ${basename} RG fix done **"

    samtools index "${fixed_bam}" && echo "  ** ${basename} RG fix index done **"
    rg_fixed_bams+=("${fixed_bam}")
done

# ----------------------------------------------------------------------
# Step 2: samtools merge
# ----------------------------------------------------------------------
echo ""
echo "--- Step 2: samtools merge ---"

merged_bam="${work_path}/merged_bam/${sample}.merged.bam"

samtools merge \
    -f \
    -@ 4 \
    "${merged_bam}" \
    "${rg_fixed_bams[@]}" && echo "** ${sample} merge done **"

samtools index "${merged_bam}" && echo "** ${sample} merged bam index done **"

# ----------------------------------------------------------------------
# Step 3: sambamba markdup
# ----------------------------------------------------------------------
echo ""
echo "--- Step 3: sambamba markdup ---"

markdup_bam="${work_path}/merged_bam/${sample}.markdup.bam"

sambamba markdup \
    --nthreads 4 \
    --tmpdir "${work_path}/tmp" \
    --overflow-list-size 2000000 \
    "${merged_bam}" \
    "${markdup_bam}" && echo "** ${sample} markdup done **"

# ----------------------------------------------------------------------
# Step 4: Clean up RG-fixed temp BAMs
# ----------------------------------------------------------------------
echo ""
echo "--- Step 4: Cleanup temp RG-fixed BAMs ---"

for f in "${rg_fixed_bams[@]}"; do
    rm -f "${f}" "${f}.bai"
done
echo "** ${sample} temp files removed **"

echo ""
echo "======================================"
echo "DONE : ${sample}"
echo "Output : ${markdup_bam}"
echo "End    : $(date)"
echo "======================================"
