# ─────────────────────────────────────────────────────────────────────────────
# EM-seq pipeline: trim → bwa-mem3 (per lane) → merge → filter → markdup
#                  → MethylDackel mbias + extract
#
# Input:  master_samples_input.csv  (generated by make_samples_csv.py)
#         columns: sample, lane, flowcell, R1, R2
# Output: MethylDackel/{sample}_CpG.methylKit  (+ CHH, CHG)
# ─────────────────────────────────────────────────────────────────────────────

import pandas as pd

configfile: "config.yaml"

WORK_DIR   = config["work_dir"]
REF_GENOME = config["ref_genome"]     # bwa-mem3 index + mark-nonconverted
REF_BUNDLE = config["ref_bundle"]     # dir containing mark-nonconverted-reads.py
REF_DACKEL = config.get("ref_methyldackel", REF_GENOME)  # MethylDackel FASTA

# ── sample table ──────────────────────────────────────────────────────────────
units = (
    pd.read_csv(config["samples_csv"])
    .assign(unit=lambda d: d["sample"] + "_" + d["flowcell"] + "_" + d["lane"])
    .set_index("unit", drop=False)
)
SAMPLES = list(units["sample"].unique())

SAMPLES = list(units["sample"].unique())

# ── wildcard constraints ───────────────────────────────────────────────────────
wildcard_constraints:
    unit   = r"[A-Za-z0-9_-]+",
    sample = r"[A-Za-z0-9_-]+"

def unit_r1(wc):  return units.loc[wc.unit, "R1"]
def unit_r2(wc):  return units.loc[wc.unit, "R2"]
def lane_bams(wc):
    u = units.loc[units["sample"] == wc.sample, "unit"]
    return expand(f"{WORK_DIR}/BWA/{{unit}}.bam", unit=u)

# ── targets ───────────────────────────────────────────────────────────────────
rule all:
    input:
        expand(f"{WORK_DIR}/MethylDackel/{{sample}}_CpG.methylKit", sample=SAMPLES),
        expand(f"{WORK_DIR}/QC/{{sample}}.flagstat", sample=SAMPLES)


# ── 1. Trim ───────────────────────────────────────────────────────────────────
rule trim_galore:
    input:
        r1 = unit_r1,
        r2 = unit_r2,
    output:
        r1 = temp(f"{WORK_DIR}/fastq_trimmed/{{unit}}_val_1.fq.gz"),
        r2 = temp(f"{WORK_DIR}/fastq_trimmed/{{unit}}_val_2.fq.gz"),
    log:   f"{WORK_DIR}/logs/trim_galore/{{unit}}.log"
    threads: 4
    shell:
        """
        module load trim_galore/0.6.6
        mkdir -p {WORK_DIR}/fastq_trimmed
        trim_galore --paired --gzip --cores {threads} \
            --basename {wildcards.unit} \
            --output_dir {WORK_DIR}/fastq_trimmed \
            {input.r1} {input.r2} \
            > {log} 2>&1
        """


# ── 2. Align per lane ─────────────────────────────────────────────────────────
rule bwa_mem3:
    input:
        r1 = f"{WORK_DIR}/fastq_trimmed/{{unit}}_val_1.fq.gz",
        r2 = f"{WORK_DIR}/fastq_trimmed/{{unit}}_val_2.fq.gz",
    output:
        temp(f"{WORK_DIR}/BWA/{{unit}}.bam")
    log:   f"{WORK_DIR}/logs/bwa/{{unit}}.log"
    params:
        rg = lambda wc: (
            "@RG\\tID:{u}\\tSM:{s}\\tCN:PMGC\\tPL:Illumina\\tLB:{s}\\tPU:{fc}_{ln}".format(
                u  = wc.unit,
                s  = units.loc[wc.unit, "sample"],
                fc = units.loc[wc.unit, "flowcell"],
                ln = units.loc[wc.unit, "lane"],
            )
        )
    threads: 4
    shell:
        """
        module load samtools/1.20
        mkdir -p {WORK_DIR}/BWA
        /cluster/home/tingliu/.conda/envs/bwa-mem3-build/bin/bwa-mem3 mem --meth -t {threads} \
            -R "{params.rg}" \
            {REF_GENOME} {input.r1} {input.r2} \
            2> {log} \
        | samtools sort -@ {threads} -m 4G -O bam -o {output} \
            >> {log} 2>&1
        """

# ── 3. Merge lane BAMs ────────────────────────────────────────────────────────
rule merge_bam:
    input:  lane_bams
    output: temp(f"{WORK_DIR}/BWA/{{sample}}.merged.bam")   # <- added temp() to save the space
    log:    f"{WORK_DIR}/logs/merge/{{sample}}.log"
    threads: 4
    shell:
        """
        module load samtools/1.20
        samtools merge -@ {threads} -f {output} {input} > {log} 2>&1
        samtools index {output} >> {log} 2>&1
        """

# ── 4. Filter non-converted reads ─────────────────────────────────────────────
rule mark_nonconverted:
    input:  f"{WORK_DIR}/BWA/{{sample}}.merged.bam"
    output:
        bam = temp(f"{WORK_DIR}/BWA/{{sample}}.filtered.bam"),
        bai = temp(f"{WORK_DIR}/BWA/{{sample}}.filtered.bam.bai"),
    log:    f"{WORK_DIR}/logs/mark_nonconverted/{{sample}}.log"
    shell:
        """
        module load samtools/1.20 python3/3.10.9
        set -o pipefail
        {REF_BUNDLE}/mark-nonconverted-reads.py \
            --reference {REF_GENOME} --bam {input} 2> {log} \
        | samtools view -b -F 512 > {output.bam} 2>> {log}
        samtools index {output.bam} >> {log} 2>&1
        """


# ── 5. Mark duplicates ────────────────────────────────────────────────────────
rule markdup:
    input:
        bam = f"{WORK_DIR}/BWA/{{sample}}.filtered.bam",
        bai = f"{WORK_DIR}/BWA/{{sample}}.filtered.bam.bai",
    output:
        bam = f"{WORK_DIR}/BWA/{{sample}}.markdup.bam",
        bai = f"{WORK_DIR}/BWA/{{sample}}.markdup.bam.bai",
    log:    f"{WORK_DIR}/logs/markdup/{{sample}}.log"
    threads: 4
    shell:
        """
        module load samtools/1.20
        module load sambamba/0.7.0
        mkdir -p {WORK_DIR}/tmp
        sambamba markdup \
            --nthreads {threads} \
            --tmpdir {WORK_DIR}/tmp \
            --overflow-list-size 2000000 \
            {input.bam} {output.bam} > {log} 2>&1
        samtools index {output.bam} >> {log} 2>&1
        samtools quickcheck {output} >> {log} 2>&1 && \
            echo "[SUCCESS] merge_bam completed: {output}" >> {log}
        """

# ── 6. BAM QC ────────────────────────────────────────────────────────
rule bam_qc:
    input:
        bam = f"{WORK_DIR}/BWA/{{sample}}.markdup.bam",
        bai = f"{WORK_DIR}/BWA/{{sample}}.markdup.bam.bai",
    output:
        flagstat = f"{WORK_DIR}/QC/{{sample}}.flagstat",
        stats    = f"{WORK_DIR}/QC/{{sample}}.stats",
    log: f"{WORK_DIR}/logs/qc/{{sample}}.log"
    threads: 4
    shell:
        """
        module load samtools/1.20
        mkdir -p {WORK_DIR}/QC
        samtools flagstat -@ {threads} {input.bam} > {output.flagstat} 2> {log}
        samtools stats    -@ {threads} {input.bam} > {output.stats}   2>> {log}
        """


# ── 7. MethylDackel mbias + extract ──────────────────────────────────────────
rule methyldackel:
    input:
        bam = f"{WORK_DIR}/BWA/{{sample}}.markdup.bam",
        bai = f"{WORK_DIR}/BWA/{{sample}}.markdup.bam.bai",
    output:
        cpg = f"{WORK_DIR}/MethylDackel/{{sample}}_CpG.methylKit",
    log:
        mbias   = f"{WORK_DIR}/logs/mbias/{{sample}}.log",
        extract = f"{WORK_DIR}/logs/extract/{{sample}}.log",
    params:
        prefix  = f"{WORK_DIR}/MethylDackel/{{sample}}",
        summary = f"{WORK_DIR}/MethylDackel/mbias_trimming_summary.tsv",
    threads: 4
    shell:
        """
        module load samtools/1.20 MethylDackel/0.6.1
        mkdir -p {WORK_DIR}/MethylDackel {WORK_DIR}/logs/mbias {WORK_DIR}/logs/extract
        bash scripts/run_methyldackel.sh \
            {params.prefix} \
            {REF_DACKEL} \
            {input.bam} \
            {threads} \
            {wildcards.sample} \
            {params.summary} \
            {log.mbias} \
            {log.extract}
        """
